### ISSUE TITLE
XCODE 9 UrlError.Code error

### ISSUE THREAD

**Issue by nkarataev** [RahulKatariya/Reactofire#19] opened 2017-06-07 10:06 UTC
Error occurred - Type 'URLError.Code' does not conform to protocol 'Hashable' in struct Retry
public var retryErrorCodes: Set<URLError.Code> = [.timedOut,
                                            .cannotFindHost,
                                            .cannotConnectToHost,
                                            .dnsLookupFailed,
                                            .networkConnectionLost
    ]

**Comment by rahul0x24** [comment] 2017-12-01 06:10
Cannot reproduce this anymore. Closing.

**Closed as completed by rahul0x24** 2017-12-01 06:10 UTC
